apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-node
spec:
  replicas: 3  # Number of storage nodes
  selector:
    matchLabels:
      app: storage-node
  template:
    metadata:
      labels:
        app: storage-node
    spec:
      containers:
      - name: storage-node
        image: your-docker-repo/storage-node:latest
        ports:
        - containerPort: 8080
        env:
        - name: NODE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: storage-node-service
spec:
  selector:
    app: storage-node
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
